import { ChatPromptTemplate } from "@langchain/core/prompts";
import { getModel } from "./model.ai.js";
import { z } from "zod";

const judgeSchema = z.object({
  solution_1_score: z.number().min(0).max(10),
  solution_2_score: z.number().min(0).max(10),
  solution_1_reasoning: z.string(),
  solution_2_reasoning: z.string(),
  winner: z.enum(["solution_1", "solution_2"]),
  overall_verdict: z.string(),
});

export type JudgeResult = z.infer<typeof judgeSchema>;

export interface BattleResult {
  problem: string;
  solution_1: string;
  solution_2: string;
  model1: string;
  model2: string;
  judgeModel: string;
  judge: JudgeResult;
}

function getModelName(modelId: string): string {
  const mapping: Record<string, string> = {
    'mistral-medium-latest': 'Mistral Medium',
    'mistral-large-latest': 'Mistral Large',
    'open-mixtral-8x22b': 'Mixtral 8x22B',
    'mistral-small-latest': 'Mistral Small',
    'command-a-03-2025': 'Cohere Command R+',
    'command-r': 'Cohere Command R',
    'command-light': 'Cohere Command Light',
    'gemini-2.5-flash': 'Gemini 2.5 Flash',
    'gemini-2.5-flash-lite': 'Gemini 2.5 Flash Lite',
    'gemini-2.5-pro': 'Gemini 2.5 Pro',
    'gemini-2.0-flash': 'Gemini 2.0 Flash',
    'gemini-1.5-flash': 'Gemini 1.5 Flash'
  };
  return mapping[modelId] || modelId;
}

export default async function runBattle(
  problem: string,
  model1Id = "mistral-medium-latest",
  model2Id = "command-a-03-2025",
  judgeModelId = "gemini-2.5-flash"
): Promise<BattleResult> {
  const m1 = getModel(model1Id);
  const m2 = getModel(model2Id);
  const jModel = getModel(judgeModelId);

  const model1Name = getModelName(model1Id);
  const model2Name = getModelName(model2Id);

  // Step 1: Both models generate solutions in parallel
  const systemInstruction = `You are an expert software engineer and system architect. You provide highly detailed, structured, and production-ready solutions.
ALWAYS format any tables strictly using GitHub Flavored Markdown (GFM) table syntax.
CRITICAL: Every single table must have a header separator row (like \`|---|---|---| \` or \`|:---|:---|:---| \`) immediately following the column headers. Never omit this row for any table under any circumstances, otherwise the table will fail to render.
Ensure there are clear empty line gaps before and after all headers, lists, tables, and code blocks.
Make sure your responses are extremely readable and use proper Markdown spacing.`;

  const solutionPrompt = ChatPromptTemplate.fromMessages([
    ["system", systemInstruction],
    ["human", "{problem}"],
  ]);

  const [mistralResponse, cohereResponse] = await Promise.all([
    solutionPrompt.pipe(m1).invoke({ problem }),
    solutionPrompt.pipe(m2).invoke({ problem }),
  ]);

  const solution_1 = typeof mistralResponse.content === "string"
    ? mistralResponse.content
    : JSON.stringify(mistralResponse.content);

  const solution_2 = typeof cohereResponse.content === "string"
    ? cohereResponse.content
    : JSON.stringify(cohereResponse.content);

  // Step 2: Judge evaluates both solutions
  const structuredJudge = (jModel as any).withStructuredOutput(judgeSchema);

  const judgePrompt = ChatPromptTemplate.fromMessages([
    [
      "system",
      `You are an expert AI judge. You evaluate two AI-generated solutions to a given problem.
Score each solution out of 10 based on correctness, clarity, completeness, and quality.
Make sure the two scores are DIFFERENT. Declare a clear winner.
Be concise but insightful in your reasoning.`,
    ],
    [
      "human",
      `Problem: {problem}

Solution 1 (generated by ${model1Name}):
{solution_1}

Solution 2 (generated by ${model2Name}):
{solution_2}

Please evaluate both solutions, score them, and provide specific reasoning. State strengths and critiques for each model by name in your reasoning.`,
    ],
  ]);

  const chain = judgePrompt.pipe(structuredJudge);

  const judgeResponse = (await chain.invoke({
    problem,
    solution_1,
    solution_2,
  })) as JudgeResult;

  return {
    problem,
    solution_1,
    solution_2,
    model1: model1Id,
    model2: model2Id,
    judgeModel: judgeModelId,
    judge: judgeResponse,
  };
}
